In [44]:
import pandas as pd
import numpy as np

### kaggle dataset link - https://www.kaggle.com/datasets/ra4u12/bookrecommendation

In [45]:
#importing BX-Books.csv
books = pd.read_csv(
    '/Users/dishitasingh/Desktop/PersonalProjects/end-to-end-recommender-system/notebook/BX-Books.csv',
    sep=';',
    encoding='latin-1',
    on_bad_lines='skip'
)

/var/folders/_t/6bkt0kq13_bdy8pnh14sjcfw0000gn/T/ipykernel_17812/3254669483.py:2: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv(

In [46]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [47]:
#taking only needed columns
books=books[['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher', 'Image-URL-L']]

In [48]:
# Lets remane some wierd columns name
books.rename(columns={
    "Book-Title": "title",
    "Book-Author": "author",
    "Year-Of-Publication": "year",
    "Publisher": "publisher",
    "Image-URL-L": "image_url"
}, inplace=True)

In [49]:
#importing BX-Users.csv
users = pd.read_csv(
    '/Users/dishitasingh/Desktop/PersonalProjects/end-to-end-recommender-system/notebook/BX-Users.csv',
    sep=';',
    encoding='latin-1',
    on_bad_lines='skip'
)

In [50]:
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [51]:
# Lets remane columns name
users.rename(columns={
    "User-ID": "user_id",
    "Location": "location",
    "Age": "age",
}, inplace=True)

In [52]:
#importing BX-Book-Ratings.csv
ratings = pd.read_csv(
    '/Users/dishitasingh/Desktop/PersonalProjects/end-to-end-recommender-system/notebook/BX-Book-Ratings.csv',
    sep=';',
    encoding='latin-1',
    on_bad_lines='skip'
)

In [53]:
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [54]:
# Lets remane columns name
ratings.rename(columns={
    "User-ID": "user_id",
    "Book-Rating": "rating",
}, inplace=True)

In [56]:
# Lets store users who had at least rated more than 200 books
x = ratings['user_id']. value_counts() > 200

In [60]:
# Now join ratings with books
ratings_with_books = ratings.merge(books, on= 'ISBN')

In [61]:
ratings_with_books.head()

,user_id,ISBN,rating,title,author,year,publisher,image_url
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...
1,276726,0155061224,5,Rites of Passage,Judith Rae,2001,Heinle,http://images.amazon.com/images/P/0155061224.0...
2,276727,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...
3,276729,052165615X,3,Help!: Level 1,Philip Prowse,1999,Cambridge University Press,http://images.amazon.com/images/P/052165615X.0...
4,276729,0521795028,6,The Amsterdam Connection : Level 4 (Cambridge ...,Sue Leather,2001,Cambridge University Press,http://images.amazon.com/images/P/0521795028.0...

In [62]:
number_rating = ratings_with_books.groupby("title")['rating'].count().reset_index()

In [63]:
number_rating

                                                    title  rating
0        A Light in the Storm: The Civil War Diary of ...       4
1                                   Always Have Popsicles       1
2                    Apple Magic (The Collector's series)       1
3        Ask Lily (Young Women of Faith: Lily Series, ...       1
4        Beyond IBM: Leadership Marketing and Finance ...       1
...                                                   ...     ...
241066                                      Ã?Â?lpiraten.       2
241067                     Ã?Â?rger mit Produkt X. Roman.       4
241068                                Ã?Â?sterlich leben.       1
241069                              Ã?Â?stlich der Berge.       3
241070                                  Ã?Â?thique en toc       2

[241071 rows x 2 columns]

In [64]:
number_rating.rename(columns={'rating':'num_of_rating'},inplace=True)

In [66]:
#merge the created number_rating with ratings_with_books

final_rating = ratings_with_books.merge(number_rating, on='title')

In [68]:
# Lets take those books which got at least 50 rating of user
final_rating = final_rating[final_rating['num_of_rating'] >= 50]

In [73]:
# lets drop the duplicates
final_rating.drop_duplicates(['user_id', 'title'], inplace=True)

/var/folders/_t/6bkt0kq13_bdy8pnh14sjcfw0000gn/T/ipykernel_17812/1204719644.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_rating.drop_duplicates(['user_id', 'title'], inplace=True)

In [75]:
final_rating

,user_id,ISBN,rating,title,author,year,publisher,image_url,num_of_rating
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,60
2,276727,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,650
6,276744,038550120X,7,A Painted House,JOHN GRISHAM,2001,Doubleday,http://images.amazon.com/images/P/038550120X.0...,838
7,276746,0425115801,0,Lightning,Dean R. Koontz,1996,Berkley Publishing Group,http://images.amazon.com/images/P/0425115801.0...,274
8,276746,0449006522,0,Manhattan Hunt Club,JOHN SAUL,2002,Ballantine Books,http://images.amazon.com/images/P/0449006522.0...,111
...,...,...,...,...,...,...,...,...,...
1031123,276704,0441007813,0,Obsidian Butterfly,Laurell K. Hamilton,2000,Ace Books,http://images.amazon.com/images/P/0441007813.0...,53
1031124,276704,0446353957,0,Mirror Image,Sandra Brown,1990,Warner Books,http://images.amazon.com/images/P/0446353957.0...,159
1031125,276704,0446605409,0,Plum Island,Nelson DeMille,1998,Warner Books,http://images.amazon.com/images/P/0446605409.0...,150
1031128,276704,0743211383,7,Dreamcatcher,Stephen King,2001,Scribner,http://images.amazon.com/images/P/0743211383.0...,481
1031129,276704,080410526X,0,All I Really Need to Know,ROBERT FULGHUM,1989,Ivy Books,http://images.amazon.com/images/P/080410526X.0...,258

In [76]:
# Lets create a pivot table
book_pivot = final_rating.pivot_table(columns='user_id',index='title',values='rating')

In [78]:
book_pivot.fillna(0,inplace=True)

In [79]:
book_pivot

user_id,8,9,14,16,17,19,23,26,32,39,...,278820,278824,278828,278832,278836,278843,278844,278846,278851,278854
title,,,,,,,,,,,,,,,,,,,,,
10 Lb. Penalty,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16 Lighthouse Road,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1984,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2010: Odyssey Two,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\Surely You're Joking, Mr. Feynman!\"": Adventures of a Curious Character""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
stardust,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [80]:
#convert to CSR matrix for easier training

from scipy.sparse import csr_matrix 
book_sparse = csr_matrix(book_pivot)

In [81]:
book_sparse

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 113483 stored elements and shape (2444, 47994)>

### Model Training

In [82]:
from sklearn. neighbors import NearestNeighbors
model = NearestNeighbors (algorithm= 'brute')

In [83]:
model.fit(book_sparse)

NearestNeighbors(algorithm='brute')

In [84]:
distance, suggestion= model.kneighbors(book_pivot.iloc[237,:].values.reshape(1,-1), n_neighbors=6 )

In [85]:
for i in range(len (suggestion)) :
    print(book_pivot.index[suggestion[i]])

Index(['Beloved (Plume Contemporary Fiction)', 'The Blooding',
       'Ground Zero and Beyond', 'A Secret Affair', 'Reasonable Doubt',
       'Blood and Gold (Rice, Anne, Vampire Chronicles.)'],
      dtype='object', name='title')

In [87]:
#keeping the books name
book_names=book_pivot.index

In [89]:
final_rating.head()

,user_id,ISBN,rating,title,author,year,publisher,image_url,num_of_rating
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,60
2,276727,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,650
6,276744,038550120X,7,A Painted House,JOHN GRISHAM,2001,Doubleday,http://images.amazon.com/images/P/038550120X.0...,838
7,276746,0425115801,0,Lightning,Dean R. Koontz,1996,Berkley Publishing Group,http://images.amazon.com/images/P/0425115801.0...,274
8,276746,0449006522,0,Manhattan Hunt Club,JOHN SAUL,2002,Ballantine Books,http://images.amazon.com/images/P/0449006522.0...,111

In [90]:
book_name = []

for book_id in suggestion:
    book_name.append(book_pivot.index[book_id])

In [91]:
book_name

[Index(['Beloved (Plume Contemporary Fiction)', 'The Blooding',
        'Ground Zero and Beyond', 'A Secret Affair', 'Reasonable Doubt',
        'Blood and Gold (Rice, Anne, Vampire Chronicles.)'],
       dtype='object', name='title')]

In [93]:
ids_index = []

for name in book_name[0]:
    ids = np.where(final_rating['title'] == name)[0][0]
    ids_index.append(ids)

In [94]:
ids_index

[np.int64(620),
 np.int64(5045),
 np.int64(13605),
 np.int64(2774),
 np.int64(1412),
 np.int64(7971)]

In [95]:
book_pivot.index[237]

'Beloved (Plume Contemporary Fiction)'

In [96]:
import os
os.makedirs('artifacts', exist_ok=True)

##    saving model

In [97]:
import pickle

pickle.dump(model, open('artifacts/model.pkl', 'wb'))
pickle.dump(book_names, open('artifacts/book_names.pkl', 'wb'))
pickle.dump(final_rating, open('artifacts/final_rating.pkl', 'wb'))
pickle.dump(book_pivot, open('artifacts/book_pivot.pkl', 'wb'))

### testing model

In [98]:
def recommend_book(book_name):
    # get index of the book
    book_id = np.where(book_pivot.index == book_name)[0][0]
    
    # get nearest neighbors
    distance, suggestion = model.kneighbors(
        book_pivot.iloc[book_id, :].values.reshape(1, -1),
        n_neighbors=6
    )
    
    # print results
    print(f"You searched: {book_name}\n")
    print("The suggestion books are:\n")
    
    for i in range(len(suggestion)):
        books = book_pivot.index[suggestion[i]]
        for j in books:
            if j != book_name:
                print(j)

In [99]:
book_name = "Harry Potter and the Chamber of Secrets (Book 2)"
recommend_book(book_name)

You searched: Harry Potter and the Chamber of Secrets (Book 2)

The suggestion books are:

Harry Potter and the Goblet of Fire (Book 4)
Harry Potter and the Prisoner of Azkaban (Book 3)
Harry Potter and the Sorcerer's Stone (Book 1)
All I Need Is You
Lucky's Lady